package gui;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import mypackage.Cardboard;
import mypackage.Type1;
import mypackage.Type2;
import mypackage.Type3;
import mypackage.Type4;
import mypackage.Type5;


/**
 *
 * @author Lee 750834
 */
public class CardboardBoxesGUI extends javax.swing.JFrame {

    // Setup interface objects and variables
    DefaultListModel basketModel = new DefaultListModel();
    private final Character[] charList = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.'};
    // Create list where cardboards will be stored
    ArrayList<Cardboard> listCardboards = new ArrayList();
    Integer counter = -1; 
    double finalCost = 0;
    boolean validInput = true;

    /**
     * Creates new form CardboardBoxesGUI
     */
    public CardboardBoxesGUI() {
        initComponents();
        initaliseInterfaceData();

        Timer timer = new Timer();
        // Create a new timer and run tasks every 0.5s
        TimerTask task = new TimerTask() {
            public void run() {
                updateFormDateTime();
                runtimeValidateCheckoutButtons();
                runtimeValidateAddOrderButtons();
            }
        };

        timer.scheduleAtFixedRate(task, 0, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoxPrintingGroup = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanelStatus = new javax.swing.JPanel();
        jLabelOrderDate = new javax.swing.JLabel();
        jLabelOrderTime = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBasket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBasketList = new javax.swing.JList<>();
        jButtonRemoveSelected = new javax.swing.JButton();
        jButtonClearBasket = new javax.swing.JButton();
        jPanelFinalCost = new javax.swing.JPanel();
        jLabelTotalOrders = new javax.swing.JLabel();
        jTextFieldTotalCost = new javax.swing.JTextField();
        jLabelTotalCost = new javax.swing.JLabel();
        jTextFieldTotalOrders = new javax.swing.JTextField();
        jButtonCheckout = new javax.swing.JButton();
        jPanelBoxDimensions = new javax.swing.JPanel();
        widthText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lengthText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        heightText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelBoxGrade = new javax.swing.JPanel();
        jComboBoxGrade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanelBoxPrinting = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanelAdditionalFeatures = new javax.swing.JPanel();
        bottomCheckBox = new javax.swing.JCheckBox();
        cornerCheckBox = new javax.swing.JCheckBox();
        sealableCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelQuantity = new javax.swing.JPanel();
        jLabelDiameterInfo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantityText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonResetOrder = new javax.swing.JButton();
        jButtonAddOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelOrderDate.setText("Order Date: dd/mm/yyy");

        jLabelOrderTime.setText("Order Time hh:mm");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTitle.setText("Group - D5 Cardboard Boxes Ordering System");

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOrderDate)
                .addGap(173, 173, 173)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOrderTime)
                .addContainerGap())
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrderDate)
                    .addComponent(jLabelOrderTime)
                    .addComponent(jLabelTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBasket.setBorder(javax.swing.BorderFactory.createTitledBorder("Basket"));

        jScrollPane1.setViewportView(jListBasketList);

        jButtonRemoveSelected.setText("Remove Selected");
        jButtonRemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveSelectedActionPerformed(evt);
            }
        });

        jButtonClearBasket.setText("Clear Basket");
        jButtonClearBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBasketLayout = new javax.swing.GroupLayout(jPanelBasket);
        jPanelBasket.setLayout(jPanelBasketLayout);
        jPanelBasketLayout.setHorizontalGroup(
            jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelBasketLayout.createSequentialGroup()
                        .addComponent(jButtonClearBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBasketLayout.setVerticalGroup(
            jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBasketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearBasket)
                    .addComponent(jButtonRemoveSelected)))
        );

        jPanelFinalCost.setBorder(javax.swing.BorderFactory.createTitledBorder("Order"));

        jLabelTotalOrders.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalOrders.setText("TOTAL ORDERS:");

        jTextFieldTotalCost.setEditable(false);
        jTextFieldTotalCost.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldTotalCost.setText("£0.00");

        jLabelTotalCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotalCost.setText("TOTAL COST:");
        jLabelTotalCost.setToolTipText("");

        jTextFieldTotalOrders.setEditable(false);
        jTextFieldTotalOrders.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldTotalOrders.setText("0");

        jButtonCheckout.setText("Checkout");

        javax.swing.GroupLayout jPanelFinalCostLayout = new javax.swing.GroupLayout(jPanelFinalCost);
        jPanelFinalCost.setLayout(jPanelFinalCostLayout);
        jPanelFinalCostLayout.setHorizontalGroup(
            jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFinalCostLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalOrders)
                    .addComponent(jLabelTotalCost))
                .addGap(35, 35, 35)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotalCost)
                    .addComponent(jTextFieldTotalOrders))
                .addContainerGap())
        );
        jPanelFinalCostLayout.setVerticalGroup(
            jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinalCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalOrders)
                    .addComponent(jTextFieldTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFinalCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalCost)
                    .addComponent(jTextFieldTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCheckout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBoxDimensions.setBorder(javax.swing.BorderFactory.createTitledBorder("Box Dimensions"));

        widthText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        widthText.setText("0.5");
        widthText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                widthTextKeyTyped(evt);
            }
        });

        jLabel1.setText("Width of box:");

        jLabel2.setText("Length of box:");

        lengthText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lengthText.setText("0.5");
        lengthText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lengthTextKeyTyped(evt);
            }
        });

        jLabel3.setText("Height of box:");

        heightText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        heightText.setText("0.5");
        heightText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightTextKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("Dimensions to be set in meters, valid range (0.5m, 10m)");

        javax.swing.GroupLayout jPanelBoxDimensionsLayout = new javax.swing.GroupLayout(jPanelBoxDimensions);
        jPanelBoxDimensions.setLayout(jPanelBoxDimensionsLayout);
        jPanelBoxDimensionsLayout.setHorizontalGroup(
            jPanelBoxDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoxDimensionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBoxDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBoxDimensionsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBoxDimensionsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lengthText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBoxDimensionsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBoxDimensionsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBoxDimensionsLayout.setVerticalGroup(
            jPanelBoxDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoxDimensionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBoxDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBoxDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lengthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBoxDimensionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanelBoxGrade.setBorder(javax.swing.BorderFactory.createTitledBorder("Box Grade"));

        jComboBoxGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setText("Cardboard grade range from 1..5");

        javax.swing.GroupLayout jPanelBoxGradeLayout = new javax.swing.GroupLayout(jPanelBoxGrade);
        jPanelBoxGrade.setLayout(jPanelBoxGradeLayout);
        jPanelBoxGradeLayout.setHorizontalGroup(
            jPanelBoxGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoxGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBoxGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxGrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBoxGradeLayout.setVerticalGroup(
            jPanelBoxGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoxGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBoxPrinting.setBorder(javax.swing.BorderFactory.createTitledBorder("Box Printing"));

        BoxPrintingGroup.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("No Colour");
        jRadioButton1.setName("0"); // NOI18N

        BoxPrintingGroup.add(jRadioButton2);
        jRadioButton2.setText("1 Colour");
        jRadioButton2.setName("1"); // NOI18N

        BoxPrintingGroup.add(jRadioButton3);
        jRadioButton3.setText("2 Colours");
        jRadioButton3.setName("2"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("Specify colour printing for the box");

        javax.swing.GroupLayout jPanelBoxPrintingLayout = new javax.swing.GroupLayout(jPanelBoxPrinting);
        jPanelBoxPrinting.setLayout(jPanelBoxPrintingLayout);
        jPanelBoxPrintingLayout.setHorizontalGroup(
            jPanelBoxPrintingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoxPrintingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBoxPrintingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanelBoxPrintingLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBoxPrintingLayout.setVerticalGroup(
            jPanelBoxPrintingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoxPrintingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBoxPrintingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAdditionalFeatures.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional Features"));

        bottomCheckBox.setText("Bottom Reinforcement");

        cornerCheckBox.setText("Corner Reinforcement");

        sealableCheckBox.setText("Sealable Tops");

        jButton1.setText("Clear Features");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 Colour", "12%"},
                {"2 Colours", "15%"},
                {"Reinforced Bottom", "13% "},
                {"Reinforced Corners", "12%"},
                {"Sealable Tops", "10%"}
            },
            new String [] {
                "Feature", "Additional Cost %"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoscrolls(false);
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelAdditionalFeaturesLayout = new javax.swing.GroupLayout(jPanelAdditionalFeatures);
        jPanelAdditionalFeatures.setLayout(jPanelAdditionalFeaturesLayout);
        jPanelAdditionalFeaturesLayout.setHorizontalGroup(
            jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomCheckBox)
                    .addComponent(sealableCheckBox)
                    .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cornerCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdditionalFeaturesLayout.setVerticalGroup(
            jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdditionalFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdditionalFeaturesLayout.createSequentialGroup()
                        .addComponent(bottomCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cornerCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sealableCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder("Box Quantity"));

        jLabelDiameterInfo1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelDiameterInfo1.setText("Valid quantities between 1 and 100");

        jLabel7.setText("Quantity of boxes for order:");

        quantityText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        quantityText.setText("1");
        quantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelQuantityLayout = new javax.swing.GroupLayout(jPanelQuantity);
        jPanelQuantity.setLayout(jPanelQuantityLayout);
        jPanelQuantityLayout.setHorizontalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuantityLayout.createSequentialGroup()
                        .addComponent(jLabelDiameterInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelQuantityLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(84, 84, 84)
                        .addComponent(quantityText)))
                .addContainerGap())
        );
        jPanelQuantityLayout.setVerticalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDiameterInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jButtonResetOrder.setText("Reset Order");
        jButtonResetOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetOrderActionPerformed(evt);
            }
        });

        jButtonAddOrder.setText("Add Order");
        jButtonAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBoxDimensions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBoxGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBoxPrinting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAdditionalFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonResetOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addComponent(jButtonAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelFinalCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBasket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBoxDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBoxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBoxPrinting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelBasket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFinalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelAdditionalFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddOrder)
                            .addComponent(jButtonResetOrder))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Reset the feature toggles.
        bottomCheckBox.setSelected(false);
        cornerCheckBox.setSelected(false);
        sealableCheckBox.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void widthTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthTextKeyTyped
        //Check non valid character input into field
        char c = evt.getKeyChar();
        List<Character> list = Arrays.asList(charList);
        if (!list.contains(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_widthTextKeyTyped

    private void lengthTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthTextKeyTyped
        //Check non valid character input into field
        char c = evt.getKeyChar();
        List<Character> list = Arrays.asList(charList);
        if (!list.contains(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_lengthTextKeyTyped

    private void heightTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightTextKeyTyped
        //Check non valid character input into field
        char c = evt.getKeyChar();
        List<Character> list = Arrays.asList(charList);
        if (!list.contains(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_heightTextKeyTyped

    private void jButtonResetOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetOrderActionPerformed
        defaultForm();
    }//GEN-LAST:event_jButtonResetOrderActionPerformed

    private void jButtonClearBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearBasketActionPerformed
        clearBasket();
    }//GEN-LAST:event_jButtonClearBasketActionPerformed

    private void quantityTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextKeyTyped
        char c = evt.getKeyChar();
        List<Character> list = Arrays.asList(charList);
        if (!list.contains(c)) { //Check non valid character input into field
            evt.consume();
        }
    }//GEN-LAST:event_quantityTextKeyTyped

    public static String verifyType(gui.Type t, ArrayList ui, String gr){
        System.out.println(ui.equals(t.getValues()));
        System.out.println(Arrays.asList(t.getPossibleGrades()).contains(gr));
        System.out.println(t.getPossibleGrades()[0]+ " " + t.getPossibleGrades()[1] + " " + t.getPossibleGrades()[2]);
        System.out.println(gr);
        if(ui.equals(t.getValues()) && Arrays.asList(t.getPossibleGrades()).contains(gr))
            return t.name();
        else
            return "Not valid";
    }
    
    /**
     * Get values from the user and store item in the list
     *
     * @author lopese
     */
    
    private void jButtonAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderActionPerformed
        // TODO add your handling code here:
        try{
            double width = Double.parseDouble(widthText.getText()); 
            double length = Double.parseDouble(lengthText.getText()); 
            double height = Double.parseDouble(heightText.getText());
            String grade = String.valueOf(jComboBoxGrade.getSelectedIndex() + 1); //make sure selected index is zero in loading
            String colour = ""; 
            for (Enumeration<AbstractButton> buttons = BoxPrintingGroup.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    colour = button.getName();
                }
            }
            boolean reBottom = false; 
            boolean reCorner = false;
            boolean sealableTop = false;
            if(bottomCheckBox.isSelected()) reBottom = true;
            if(cornerCheckBox.isSelected()) reCorner = true;
            if(sealableCheckBox.isSelected()) sealableTop = true;
            Integer quantity = Integer.parseInt(quantityText.getText());
            String type = "Not valid";

            ArrayList userInput = new ArrayList();
            userInput.add(colour);
            userInput.add(reBottom);
            userInput.add(reCorner);

            for (gui.Type currentType : gui.Type.values()) { 
                 type = verifyType(currentType, userInput, grade);
                 if(type != "Not valid")
                     break;
            }

            switch(type){
                case "ONE":{
                    Type1 cardboard1 = new Type1(width, length, height, grade, sealableTop, quantity);
                    listCardboards.add(cardboard1);
                    break;
                }
                case "TWO":{
                    Type2 cardboard2 = new Type2(width, length, height, grade, colour, sealableTop, quantity);   
                    listCardboards.add(cardboard2);
                    break;
                }
                case "THREE":{
                    Type3 cardboard3 = new Type3(width, length, height, grade, colour, sealableTop, quantity);     
                    listCardboards.add(cardboard3);
                    break;
                }
                case "FOUR":{
                    Type4 cardboard4 = new Type4(width, length, height, grade, colour, reBottom, sealableTop, quantity); 
                    listCardboards.add(cardboard4);
                    break;
                }
                case "FIVE":{
                    Type5 cardboard5 = new Type5(width, length, height, grade, colour, reBottom, reCorner, sealableTop, quantity);      
                    listCardboards.add(cardboard5);
                    break;
                }
                default:{ 
                    JOptionPane.showMessageDialog(null, "Type not valid!");
                    break;
                }
            }
            if(type != "Not valid"){ //update total cost and anything else function
                counter++;
                basketModel.add(counter, "First order: " + listCardboards.get(counter).getInformation());
                finalCost += listCardboards.get(counter).getCost();//to be changed maybe
                jTextFieldTotalOrders.setText(String.valueOf(listCardboards.size()));
                jTextFieldTotalCost.setText("£" + String.format("%.2f", finalCost));
            }
        }
        catch(Exception ex ){ JOptionPane.showMessageDialog(null, ex.toString()); }
    }//GEN-LAST:event_jButtonAddOrderActionPerformed

    private void jButtonRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSelectedActionPerformed
        // TODO add your handling code here:
        int index = jListBasketList.getSelectedIndex();
        finalCost -= listCardboards.get(index).getCost();
        basketModel.remove(index);
        listCardboards.remove(index);
        counter--;
        jTextFieldTotalOrders.setText(String.valueOf(listCardboards.size()));
        jTextFieldTotalCost.setText("£" + String.format("%.2f", finalCost));
    }//GEN-LAST:event_jButtonRemoveSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardboardBoxesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardboardBoxesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardboardBoxesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardboardBoxesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardboardBoxesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BoxPrintingGroup;
    private javax.swing.JCheckBox bottomCheckBox;
    private javax.swing.JCheckBox cornerCheckBox;
    private javax.swing.JTextField heightText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddOrder;
    private javax.swing.JButton jButtonCheckout;
    private javax.swing.JButton jButtonClearBasket;
    private javax.swing.JButton jButtonRemoveSelected;
    private javax.swing.JButton jButtonResetOrder;
    private javax.swing.JComboBox<String> jComboBoxGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDiameterInfo1;
    private javax.swing.JLabel jLabelOrderDate;
    private javax.swing.JLabel jLabelOrderTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTotalCost;
    private javax.swing.JLabel jLabelTotalOrders;
    private javax.swing.JList<String> jListBasketList;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdditionalFeatures;
    private javax.swing.JPanel jPanelBasket;
    private javax.swing.JPanel jPanelBoxDimensions;
    private javax.swing.JPanel jPanelBoxGrade;
    private javax.swing.JPanel jPanelBoxPrinting;
    private javax.swing.JPanel jPanelFinalCost;
    private javax.swing.JPanel jPanelQuantity;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldTotalCost;
    private javax.swing.JTextField jTextFieldTotalOrders;
    private javax.swing.JTextField lengthText;
    private javax.swing.JTextField quantityText;
    private javax.swing.JCheckBox sealableCheckBox;
    private javax.swing.JTextField widthText;
    // End of variables declaration//GEN-END:variables

    /**
     * Initialise the interface with default data
     *
     * @author Lee 750834
     */
    public void initaliseInterfaceData() {
        updateFormDateTime();
        setupBasketList();
    }

    /**
     * Resets the form values
     *
     * @author Lee 750834
     */
    private void defaultForm() {
        widthText.setText("0.5");
        lengthText.setText("0.5");
        heightText.setText("0.5");
        quantityText.setText("1");
        jRadioButton1.setSelected(true);
        bottomCheckBox.setSelected(false);
        cornerCheckBox.setSelected(false);
        sealableCheckBox.setSelected(false);
        jComboBoxGrade.setSelectedIndex(0);
    }

    /**
     * Create a new basket list model
     *
     * @author Lee 750834
     */
    private void setupBasketList() {
        jListBasketList.setModel(basketModel);
    }

    /**
     * Clear the basket and update the UI with default order data
     *
     * @author Lee 750834
     */
    public void clearBasket() {
        listCardboards.clear();
        counter = -1;
        finalCost = 0;
        basketModel.clear();
        jTextFieldTotalOrders.setText(String.valueOf(listCardboards.size()));
        jTextFieldTotalCost.setText("£" + String.valueOf(finalCost));
    }

    /**
     * Checks the condition of the basket for valid access.
     *
     * @author Lee 750834
     */
    public void runtimeValidateCheckoutButtons() {
        // check total orders from order 
        // enable and disable if < 0 .. something
    }

    /**
     * Checks the conditions of the order and enables or disables buttons.
     *
     * @author Lee 750834
     */
    public void runtimeValidateAddOrderButtons() {
        try {
            String boxQuantityString = quantityText.getText();
            String widthString = widthText.getText();
            String heightString = heightText.getText();
            String lengthSrting = lengthText.getText();
            if (!boxQuantityString.isEmpty() && !widthString.isEmpty() && !heightString.isEmpty() && !lengthSrting.isEmpty()) {
                int boxQuantity = Integer.parseInt(quantityText.getText());
                if (listCardboards.size() >= 20 || boxQuantity == 0 || boxQuantity > 100 || !controlSizes(lengthSrting) || !controlSizes(heightString) || !controlSizes(widthString)) {
                    jButtonAddOrder.setEnabled(false);
                } else {
                    jButtonAddOrder.setEnabled(true);
                }
            }
            else jButtonAddOrder.setEnabled(false);
        } catch (Exception error) {
            quantityText.setText("1");
            String errorText = "Ensure the quantity input is not empty or is a decimal number";
            displayErrorModal("Invalid Box Inputs", errorText + " " + error);
        }
        
    }
    
    public boolean controlSizes(String currentSize){
        boolean valid = false;
        double sizeValue = Double.parseDouble(currentSize);
        if (sizeValue  >= 0.5 && sizeValue <= 10 ) valid = true;
        return valid;
    }

    /**
     * Display an error modal showing error information based on its parameters
     *
     * @author Lee 750834
     */
    public void displayErrorModal(String errorTitle, String errorDescription) {
        JOptionPane.showMessageDialog(this, errorDescription, errorTitle, JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Update the date and time within the form every mouse click.
     *
     * @author Lee 750834
     */
    public void updateFormDateTime() {
        Date date = new Date();
        SimpleDateFormat simpleTime = new SimpleDateFormat("kk:mm");
        SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yyy");
        jLabelOrderTime.setText(simpleTime.format(date));
        jLabelOrderTime.setText("Order Time: " + simpleTime.format(date));
        jLabelOrderDate.setText("Order Date: " + simpleDate.format(date));
    }
}
